### ISSUE TITLE
Installation via `conda`

### ISSUE THREAD

**Issue by phobson** [perrygeo/python-raster-stats#53]
Hey Matt,

Would you be interested in making this available through `conda` via binstar?

I'd be happy to provide a recipe (either as a PR or simply provide the downloads via my channel on binstar).

**Comment by perrygeo** [comment]
Very interested. I don't have any experience with binstar/conda packaging but would love to learn via pull request.

**Comment by timcera** [comment]
For linux, I already have conda packages that you can install with

    conda install -c https://conda.binstar.org/timcera rasterstats

This is rasterstats 0.5 and supports Python 2.7, 3.3, and 3.4.

I named the package rasterstats to match the name on PyPI.

Might be easy enough to have Windows versions also - will have to figure that out.

All I did was:

    conda skeleton pypi rasterstats
    conda build rasterstats
    conda install -y -n py2.7 -c timcera rasterstats

There is a way to configure conda to have all 'conda install ...' commands automatically upload packages to binstar, and the '-n py2.7' option is to install into my local 2.7 environment.

Kindest regards,
Tim

**Comment by phobson** [comment]
Good to know, I'm having trouble with the `dopopt` dependency on windows. Maybe using `conda skeleton` will help

**Comment by perrygeo** [comment]
@phobson The `docopt` dependency will go away in 0.6 (it's only for the CLI `rasterstats` script which is not maintained and will likely be replaced in future versions)

**Comment by perrygeo** [comment]
Are there any remaining blocking issues to getting this in conda?
