### ISSUE TITLE
Speeding calculations

### ISSUE THREAD

**Issue by lou-a** [perrygeo/python-raster-stats#54]
Hello,
I have just started using rasterstats (which works great!).
I am working with a very large amount of rasters for which I have to get averages based on a single shapefile.
I wondered if there was a fairly trivial way to accelerate this process by keeping the shapefile features extents and masks in memory instead of calculating them for every raster?
Thanks!

**Comment by perrygeo** [comment]
That's a very good idea. Originally rasterstats was designed to work against a single raster at a time but in  I often run into the same situation where I need stats against multiple rasters. I've already started a ticket to address this limitation but haven't started implementing it yet - the design decisions and discussion will happen over at issue #32
