### ISSUE TITLE
minority and majority stats return non-serializable types

### ISSUE THREAD

**Issue by perrygeo** [perrygeo/python-raster-stats#67]
minority and majority both return <type 'numpy.float32'> and give an error when trying to run json.dumps():

    TypeError: 14.148893 is not JSON serializable

**Comment by brendan-ward** [comment]
You probably already know this, but in case it helps:

```json``` library doesn't like ```numpy``` types.  Just cast those to python ```float``` before calling ```json.dumps()```

**Comment by perrygeo** [comment]
Thanks @brendan-ward That was definitely the issue. Strange that numpy scalars don't automatically cast to their respective python types when serialized... but explicit casting to float works for this particular case.
